# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Session configuration
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        # Session timeout: 30 minutes of inactivity
        gc_maxlifetime: 1800
        # Session cookie lifetime: 1 hour
        cookie_lifetime: 3600

    # Router configuration for subdirectory deployment
    router:
        default_uri: '%env(APP_URL)%'

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        csrf_protection: true
        form: true
        validation:
            enable_attributes: true   # (ou enable_annotations selon ta version)
        


