vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        exercise_video:
            uri_prefix: /uploads/exercises/videos
            upload_destination: '%kernel.project_dir%/public/uploads/exercises/videos'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true