vich_uploader:
    db_driver: orm
    mappings:
        diplomas:
            uri_prefix: /uploads/diplomas
            upload_destination: '%kernel.project_dir%/public/uploads/diplomas'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
